stages:
  - test


firefox:
    tags:
        - backend
    image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    stage: test
    script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run build; npm start &
    # run Cypress tests
    - npx cypress run --browser firefox

googlechrome:
    tags:
        - backend
    image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    stage: test
    script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run build; npm start &
    # run Cypress tests
    - npx cypress run --browser firefox